export default {
  test: 'Test',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  cancel: 'Cancel',
  save: 'Save',
  confirm: 'Confirm',
  close: 'Close',
  update: 'Update',
  search: 'Search',
  reset: 'Reset',
  copy: 'Copy',
  login: 'Login',
  logout: 'Quit',
  signup: 'Register',
  profile: 'Profile',
  setting: 'Setting',
  menu: 'Menu',
  home: 'Home',
  username: 'Username',
  password: 'Password',
  email: 'Email',
  phone: 'Phone',
  sex: 'Sex',
  birthday: 'Birthday',
  nickname: 'Nickname',
  remark: 'Remarks',
  status: 'Status',
  role: 'Role',
  permission: 'Permission',
  about: 'About',
  version: 'Version',
  copyright: 'Copyright',
  user_manage: 'User Management',
  role_manage: 'Role Management',
  permission_manage: 'Permission Management',
  menu_manage: 'Menu Management',
  log_manage: 'Log Management',
  system_manage: 'System Management',
  system_config: 'System Configuration',
  module: 'Module',
  keyword: 'Keyword',
  pagination: 'Page',
  page_size: 'Page Size',
  current_page: 'Current Page',
  page_total: 'Page Count',
  page_total_count: 'Total',
  asset_manage: 'Asset Management',
  asset: 'Asset',
  asset_type: 'Asset Type',
  asset_category: 'Asset Category',
  asset_status: 'Asset Status',
  asset_list: 'Asset List',
  asset_add: 'Add Asset',
  asset_edit: 'Edit Asset',
  asset_delete: 'Delete Asset',
  asset_detail: 'Asset Details',
  asset_log: 'Asset Log',
  report: 'Report',
  report_manage: 'Report Management',
  report_list: 'Report List',
  report_add: 'Add Report',
  report_edit: 'Edit Report',
  report_delete: 'Delete Report',
  report_detail: 'Report Details',
  report_log: 'Report Log',
  dashboard: 'Dashboard',
  dashboard_manage: 'Dashboard Management',
  dashboard_list: 'Dashboard List',
  dashboard_add: 'Add Dashboard',
  dashboard_edit: 'Edit Dashboard',
  dashboard_delete: 'Delete Dashboard',
  dashboard_detail: 'Dashboard Details',
  dashboard_log: 'Dashboard Logs'
};
